# Rustfmt configuration file
# See https://rust-lang.github.io/rustfmt/ for options

max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Auto"
use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2024"
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = true
force_explicit_abi = true
format_code_in_doc_comments = true
normalize_comments = true
wrap_comments = true
comment_width = 80
